# Generated by Django 5.0.6 on 2024-06-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Independiente',
            fields=[
                ('numero_identificacion', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('Cc', 'Cedula de ciudadania'), ('Ce', 'Cedula de extrangeria'), ('Passpor', 'Pasaporte')], max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('P', 'Prefiero no decir')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_exp_documento', models.DateField()),
                ('imagen', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
