# Generated by Django 5.0.6 on 2024-06-12 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos', models.IntegerField(default=0)),
                ('estado_u', models.BooleanField(default=True)),
                ('contrasena', models.CharField(max_length=128, null=True)),
                ('id_rol', models.CharField(choices=[('Independiente', 'Independiente')], max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Independientes.independiente')),
            ],
        ),
    ]
