# Generated by Django 5.0.6 on 2024-06-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0002_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='numero_identificacion',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
