# Generated by Django 5.0.6 on 2024-06-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0003_alter_independiente_numero_identificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'permissions': [('ver_pagina_registro', 'Puede ver la página de registro de independientes'), ('editar_empleado', 'Puede editar empleados')]},
        ),
    ]
