# Generated by Django 5.0.6 on 2024-06-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0004_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='documento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
