# Generated by Django 5.0.6 on 2024-06-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0006_alter_usuarios_options_usuarios_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
    ]
