# Generated by Django 5.0.6 on 2024-06-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0010_passwordresetrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
