# Generated by Django 5.0.6 on 2024-06-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0011_alter_usuarios_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
