# Generated by Django 5.0.6 on 2024-06-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0012_alter_usuarios_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='independiente',
            name='fecha_ingreso',
        ),
    ]
