# Generated by Django 5.0.6 on 2024-06-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0013_remove_independiente_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCalculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarioBase', models.FloatField(blank=True, null=True)),
                ('ibc', models.FloatField(blank=True, null=True)),
                ('salud', models.FloatField(blank=True, null=True)),
                ('pension', models.FloatField(blank=True, null=True)),
                ('arl', models.CharField(blank=True, choices=[('0', 'Ninguno'), ('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], max_length=50, null=True)),
                ('CCF', models.CharField(blank=True, choices=[('Ninguna ', 'Ninguno'), ('Si', 'Si')], max_length=50, null=True)),
                ('FSP', models.FloatField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Independientes.independiente')),
            ],
        ),
    ]
