# Generated by Django 5.0.6 on 2024-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0014_datoscalculos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculos',
            old_name='cesantias',
            new_name='FSP',
        ),
        migrations.RemoveField(
            model_name='calculos',
            name='interesCesantias',
        ),
        migrations.RemoveField(
            model_name='calculos',
            name='vacaciones',
        ),
        migrations.AlterField(
            model_name='datoscalculos',
            name='pension',
            field=models.FloatField(default=16, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datoscalculos',
            name='salud',
            field=models.FloatField(default=12.5, max_length=50, null=True),
        ),
    ]
