# Generated by Django 5.0.6 on 2024-06-16 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0015_rename_cesantias_calculos_fsp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscalculos',
            name='ibc',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(40)]),
        ),
    ]
