# Generated by Django 5.0.6 on 2024-06-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0017_alter_datoscalculos_ibc_alter_datoscalculos_pension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='numero_identificacion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
