# Generated by Django 5.0.6 on 2024-06-07 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('telefono_entidad', models.CharField(max_length=15)),
                ('correo_entidad', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numero_identificacion', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('Cc', 'Cedula de ciudadania'), ('Ce', 'Cedula de extrangeria'), ('Passpor', 'Pasaporte')], max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('P', 'Prefiero no decir')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_exp_documento', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos', models.IntegerField(blank=True, default=0)),
                ('estado_u', models.BooleanField(blank=True, default=True)),
                ('contrasena', models.CharField(blank=True, max_length=128, null=True)),
                ('id_rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Contador', 'Contador'), ('Auxiliar Contable', 'Auxiliar Contable'), ('RRHH', 'RRHH'), ('Empleado General', 'Empleado General')], max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
    ]
