# Generated by Django 5.0.6 on 2024-06-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='numero_identificacion',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
