# Generated by Django 5.0.6 on 2024-06-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0002_alter_empleado_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado_u',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
