# Generated by Django 5.0.6 on 2024-06-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0003_alter_usuarios_contrasena_alter_usuarios_estado_u_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
