# Generated by Django 5.0.6 on 2024-06-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0004_alter_usuarios_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
