# Generated by Django 5.0.6 on 2024-06-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0007_alter_usuarios_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='numero_identificacion',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
