# Generated by Django 5.0.6 on 2024-06-13 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0008_alter_empleado_numero_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud', models.FloatField(blank=True, null=True)),
                ('pension', models.FloatField(blank=True, null=True)),
                ('arl', models.FloatField(blank=True, null=True)),
                ('salarioBase', models.FloatField(blank=True, null=True)),
                ('cajaCompensacion', models.FloatField(blank=True, null=True)),
                ('cesantias', models.FloatField(blank=True, null=True)),
                ('interesCesantias', models.FloatField(blank=True, null=True)),
                ('vacaciones', models.FloatField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HorasExDiu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('HorasExNoc', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('HorasExFestivaDiu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('HorasExFestivaNoc', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('recargoDiuFes', models.IntegerField(blank=True, null=True)),
                ('recargoNoc', models.IntegerField(blank=True, null=True)),
                ('recargoNocFest', models.IntegerField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
    ]
