# Generated by Django 5.0.6 on 2024-06-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0009_calculos_novedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nivel_riesgo',
            field=models.CharField(blank=True, choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], max_length=10, null=True),
        ),
    ]
