# Generated by Django 5.0.6 on 2024-06-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0010_empleado_fecha_ingreso_empleado_nivel_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empresa'),
        ),
    ]
