# Generated by Django 5.0.6 on 2024-06-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0013_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='numero_identificacion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
