# Generated by Django 5.0.6 on 2024-06-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0014_alter_empleado_numero_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculos',
            name='fecha_calculos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='fecha_novedad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
