# Generated by Django 5.0.6 on 2024-06-17 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0015_calculos_fecha_calculos_novedades_fecha_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculos',
            name='arl',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='cajaCompensacion',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='cesantias',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='dias_vacaciones',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='fecha_calculos',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='icbf',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='interesCesantias',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='pension',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='salarioBase',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='salud',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='sena',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='transporte',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calculos',
            name='vacaciones',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nivel_riesgo',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1300000)]),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='fecha_novedad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
