# Generated by Django 5.0.6 on 2024-06-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0016_alter_calculos_arl_alter_calculos_cajacompensacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=88, null=True),
        ),
    ]
