# Generated by Django 5.0.6 on 2024-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0017_alter_usuarios_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculos',
            name='HorasExDiu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculos',
            name='HorasExFestivaDiu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculos',
            name='HorasExFestivaNoc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculos',
            name='HorasExNoc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculos',
            name='recargoDiuFes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculos',
            name='recargoNoc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculos',
            name='recargoNocFest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
